Install database optimization
yunionio/ocboot pull request #306
Opened 2022-01-11 11:57 UTC by z-yfgit

Database optimization for installation and automated deployment of high availability databases

2022-01-13 03:48 UTC, zexi commented on README.md
> +mariadb_ha_node:
这个配置放到 primary_master_node 上面吧，ha_node 应该是在 primary_master_node 之前部署的，放上去容易理解点

2022-01-13 03:51 UTC, zexi commented on lib/ocboot.py
> +        self.mariadb_ha_config = self._fetch_conf(MariadbHAConfig)
这里需要判断下，如果同时设置了 mariadb_config 和 mariadb_ha_config 的话，需要报错退出，告诉用户这两个配置不能同时设置

2022-01-13 03:51 UTC, zexi commented on lib/ocboot.py
> +    @classmethod
这里应该空一行

2022-01-17 02:00 UTC, zhasm commented on onecloud/roles/mariadb/tasks/10ha.yml
> +    mode: pull
文件结尾空一行，否则 github 有 warning.

2022-01-17 09:32 UTC, zexi requested changes

2022-01-17 09:32 UTC, zexi commented on README.md
> +mariadb_ha_node:
mariadb_ha_nodes ，需要用复数

2022-01-19 07:47 UTC, merged